# Generated by Django 6.0.5 on 2026-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akb', models.PositiveIntegerField(help_text='Акб')),
                ('storage', models.IntegerField(choices=[(64, '64 GB'), (128, '128 GB'), (256, '256 GB'), (512, '512 GB'), (1024, '1 TB')], default=128, help_text='Память')),
                ('color', models.CharField(max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('ideal', 'Идеальное'), ('good', 'Хорошее')], default='ideal', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='iphone_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
